apiVersion: skaffold/v4beta4
kind: Config
build:
  artifacts:
  - image: code.org
    sync:
      infer:
      # rerun watching
      # /app/src/lib, /app/src/shared/middleware, /app/src/dashboard/legacy, /app/src/pegasus for **/*.{rb,ru,yml} (ignoring **/migrations/*.rb,test/**/*.rb)
      - '**/*.rb'
      - '**/*.ru'
      - '**/*.yml'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
    docker:
      dockerfile: ./k8s/code.org.dockerfile
      cacheFrom:
      - code.org
      - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org:staging
    requires:
    - image: code.org-static
      alias: CODE_ORG_STATIC
    - image: code.org-db-seed
      alias: CODE_ORG_DB_SEED
  - image: code.org-static
    docker:
      dockerfile: ./k8s/code.org-static.dockerfile
      cacheFrom:
      - code.org-static
      - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-static:staging
  - image: code.org-db-seed
    docker:
      dockerfile: ./k8s/code.org-db-seed.dockerfile
      cacheFrom:
      - code.org-db-seed
      - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-db-seed:staging
  local:
    useBuildkit: true # required for caching layers, see https://github.com/moby/moby/issues/34715#issuecomment-589655390

profiles:
- name: development
  activation:
    - command: dev
    - kubeContext: docker-desktop
  deploy:
    kubectl:
      hooks:
        before:
          - host:
              # we create the storage objects in k8s/code.org/persistent-storage using
              # a pre-deploy hook, so they aren't destroyed when `skaffold dev` quits
              command: [
                "sh", "-c", 
                "kubectl apply -f k8s/code.org/raw/persistent --context=$SKAFFOLD_KUBE_CONTEXT --namespace=$SKAFFOLD_NAMESPACES"
              ]

- name: dev-raw
  manifests:
    rawYaml:
    - ./k8s/code.org/raw/*.yaml

- name: dev-kustomize
  manifests:
    kustomize:
      paths:
      - ./k8s/code.org/kustomize/development

portForward:
- resourceType: Deployment
  resourceName: dashboard
  port: 3000
- resourceType: StatefulSet
  resourceName: db
  port: 3306
# - resourceType: deployment
#   resourceName: svc/kubernetes-dashboard-nginx-controller
#   port: 8443:443