apiVersion: skaffold/v4beta4
kind: Config
build:
  # tagPolicy:
  #   gitCommit:
  #     ignoreChanges: true

  # For dev ease atm, adds :latest, switch to gitCommit policy long term
  tagPolicy:
    sha256: {}
  
  artifacts:
  - image: code.org
    sync:
      infer:
      # rerun watching
      # /app/src/lib, /app/src/shared/middleware, /app/src/dashboard/legacy, /app/src/pegasus for **/*.{rb,ru,yml} (ignoring **/migrations/*.rb,test/**/*.rb)
      - '**/*.rb'
      - '**/*.ru'
      - '**/*.yml'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
    docker:
      dockerfile: ./k8s/code.org.dockerfile
      cacheFrom:
      - code.org
      - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org:staging
    requires:
    - image: code.org-static
      alias: CODE_ORG_STATIC
  - image: code.org-static
    docker:
      dockerfile: ./k8s/code.org-static.dockerfile
      cacheFrom:
      - code.org-static
      - 475661607190.dkr.ecr.us-east-1.amazonaws.com/code.org-static:staging
  local:
    useBuildkit: true # required for caching layers, see https://github.com/moby/moby/issues/34715#issuecomment-589655390
deploy:
  docker:
    images:
    - code.org

portForward:
- resourceType: Container
  resourceName: code.org
  port: 3000