AWSTemplateFormatVersion: 2010-09-09
Description: Resources for the dsco.code.org design system

Parameters:
  BucketName:
    Type: String
    Default: cdo-dsco
  Domain:
    Type: String
    Default: code.org
  Subdomain:
    Type: String
    Default: dsco
  DomainName:
    Type: String
    Default: dsco.code.org

Resources:

  SubdomainNameserverRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: code.org
      Type: NS


  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref DomainName

  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZone

  DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Ref HostedZone
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt
          - CloudfrontDistribution
          - DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  CloudfrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub '${Subdomain}.${Domain}'
        Enabled: true
        DefaultCacheBehavior:
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          TargetOriginId: !Sub 's3-${BucketName}'
          ViewerProtocolPolicy: https-only
        Origins:
          - DomainName: !Sub '${BucketName}.s3.amazonaws.com'
            Id: !Sub 's3-${BucketName}'
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: !Ref SSLCertificate
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
      Tags:
        - Key: environment
          Value: production

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Ref BucketName
      CorsConfiguration:
        CorsRules:
          - AllowedMethods: [GET]
            AllowedOrigins:
              - !Sub "*.${Domain}"
              - '*.code.org:3000'
              - 'http://localhost-studio.code.org:*'
            AllowedHeaders: ['*']
      Tags:
        - Key: environment
          Value: production

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
