---
AWSTemplateFormatVersion: 2010-09-09
Description: Provisions domains & subdomains that need to redirect to other domains or URL's. Uses Cloudfront Functions.

Parameters:
  CodeDotOrgHostedZone:
    Type: String
    Description: Hosted Zone ID for code.org

Resources:

  # -----------------------------------
  # Cloudfront Function
  # -----------------------------------

  RedirectFunction:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-redirect-function"
      FunctionConfig: 
        Comment: Redirects various domains
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var redirectTo = function (newUrl) {
            return {
                statusCode: 301,
                statusDescription: '301 Redirect',
                headers: {
                  "location": { "value": "https://" + newUrl },
                },
            };
          }

          var redirectsToRoot = {
            "learn.code.org": "code.org",
            "hourofcode.co": "hourofcode.com",
            "hourofcode.net": "hourofcode.com",
            "hourofcode.co.uk": "hourofcode.com",
            "hourofcode.org.uk": "hourofcode.com",
            "onehourofcode.com": "hourofcode.com",
            "onehourofcode.org": "hourofcode.com",
            "dayofcode.com": "hourofcode.com",
            "dayofcode.org": "hourofcode.com",
            "monthofcode.com": "hourofcode.com",
            "weekofcode.org": "hourofcode.com",
            "weekofcode.com": "hourofcode.com",
            "yearofcode.co.uk": "uk.code.org",
            "yearofcode.org.uk": "uk.code.org",
            "forums.code.org": "support.code.org",
            "blockly.com": "studio.code.org",
            "learn.code.org": "studio.code.org",
            "aws.code.org": "code.org",
            "csedweek.com": "csedweek.org",
            "csedweek.net": "csedweek.org",
            "cseducationweek.com": "csedweek.org",
            "cseducationweek.org": "csedweek.org",
            "ceosforcs.net": "ceosforcs.com",
            "ceosforcs.org": "ceosforcs.com",
          }

          var redirectsWithPaths = {
            "hourofcode.org": "hourofcode.com",
          } 

          if (redirectsToRoot[event.origin.domainName]) {
            return redirectTo(redirectsToRoot[event.origin.domainName])
          } else if (redirectsWithPaths[event.origin.domainName]) {
            return redirectTo(redirectsWithPaths[event.origin.domainName] + event.request.uri)
          }
        };

  # -----------------------------------
  # Hosted Zones and Record Set Groups
  # 
  # - All hosted zones are set to 'retain' in case manual records have been added
  # - Many hosted zones have been manually created, and will need to be imported
  #   into this stack, or deleted and replaced by this stack.
  # -----------------------------------

  LearnDotCodeDotOrgRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref CodeDotOrgHostedZone
      RecordSets:
      - Name: learn.code.org
        Type: A
        AliasTarget:
          DNSName: !GetAtt [RedirectDistribution1, DomainName]
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases

  HourofcodeDotCoHostedZone:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.co

  HourofcodeDotCoRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HourofcodeDotCoHostedZone
      RecordSets:
      - Name: hourofcode.co
        Type: A
        AliasTarget:
          DNSName: !GetAtt [RedirectDistribution1, DomainName]
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
      - Name: www.hourofcode.co
        Type: A
        AliasTarget:
          DNSName: hourofcode.co

  HourofcodeDotOrgHostedZone:
    Type: "AWS::Route53::HostedZone"
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.org

  HourofcodeDotOrgRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HourofcodeDotCoHostedZone
      RecordSets:
      - Name: hourofcode.org
        Type: A
        AliasTarget:
          DNSName: !GetAtt [RedirectDistribution1, DomainName]
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
      - Name: www.hourofcode.org
        Type: A
        AliasTarget:
          DNSName: hourofcode.org

  # -----------------------------------
  # Cloudfront Distributions
  #
  # Note that SSL certificates support a max of 10 alternative names, so we must
  # create a new distribution for each group of 11 domains.
  # -----------------------------------

  RedirectDistribution1:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Redirects via CloudFront functions
        PriceClass: PriceClass_All
        Aliases:
          - learn.code.org
          - hourofcode.co
          - hourofcode.org
        Origins:
          # An origin is required, but will never receive traffic
          - Id: PrimaryOrigin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        DefaultCacheBehavior:
          TargetOriginId: PrimaryOrigin
          CachePolicyId: !Ref RedirectCachePolicy
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Ref RedirectFunction
          ViewerProtocolPolicy: allow-all
          # Use shared Realtime Log config
          RealtimeLogConfigArn: !ImportValue AccessLogs-Config
        ViewerCertificate:
          AcmCertificateArn: !Ref RedirectCertificate1
          SslSupportMethod: sni-only

  RedirectCertificate1:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: learn.code.org
      SubjectAlternativeNames:
        - hourofcode.org
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: learn.code.org
          HostedZoneId: !Ref CodeDotOrgHostedZone
        - DomainName: hourofcode.co
          HostedZoneId: !Ref HourOfCodeDotOrgHostedZone
        - DomainName: hourofcode.org
          HostedZoneId: !Ref HourOfCodeDotCoHostedZone

  # -----------------------------------
  # Common Resources
  # -----------------------------------

  # This cache policy is shared by all Cloudfront Distributions in this stack.
  RedirectCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-redirect-policy"
        MinTTL: 3600
        MaxTTL: 31536000
        DefaultTTL: 86400
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          CookiesConfig: 
            CookieBehavior: none
          HeadersConfig: 
            HeaderBehavior: whitelist
            Headers:
              - Origin
          QueryStringsConfig: 
            QueryStringBehavior: all
