---
AWSTemplateFormatVersion: 2010-09-09
Description: Provisions domains & subdomains that need to redirect to other domains or URL's. Uses Cloudfront Functions.

# TODO
#   - add more recordset groups for the other hosted zones

Resources:

  # -----------------------------------
  # Cloudfront Function
  # -----------------------------------

  RedirectFunction:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-redirect-function"
      FunctionConfig: 
        Comment: Redirects various domains
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var redirects = {
            "hourofcode.co": "hourofcode.com",
            "hourofcode.net": "hourofcode.com",
            "hourofcode.co.uk": "hourofcode.com",
            "hourofcode.org.uk": "hourofcode.com",
            "onehourofcode.com": "hourofcode.com",
            "onehourofcode.org": "hourofcode.com",
            "dayofcode.com": "hourofcode.com",
            "dayofcode.org": "hourofcode.com",
            "monthofcode.com": "hourofcode.com",
            "weekofcode.org": "hourofcode.com",
            "weekofcode.com": "hourofcode.com",
            "www.hourofcode.com": "hourofcode.com"
          }
          var newUrl = redirects[event.origin.domainName]
          var newUrl = 'https://code.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # -----------------------------------
  # Hosted Zones and Record Set Groups
  # -----------------------------------

  HourofcodeDotCoHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.co

  HourofcodeDotCoRecords:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HourofcodeDotCoHostedZone
      RecordSets:
      - Name: hourofcode.co
        Type: A
        AliasTarget:
          DNSName: !GetAtt [HourofcodeDotComRedirectDistribution1, DomainName]
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases


  HourofcodeDotNetHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.net


  HourofcodeDotCoDotUkHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.co.uk


  HourofcodeDotOrgDotUkHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: hourofcode.org.uk


  OnehourofcodeDotComHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: onehourofcode.com


  OnehourofcodeDotOrgHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: onehourofcode.org


  DayofcodeDotComHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: dayofcode.com


  DayofcodeDotOrgHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: dayofcode.org


  MonthofcodeDotComHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: monthofcode.com


  WeekofcodeDotOrgHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: weekofcode.org


  WeekofcodeDotComHostedZone:
    Type: "AWS::Route53::HostedZone"
    # Hosted zones will not be deleted upon stack deletion in case other records have been added.
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Name: weekofcode.com


  # -----------------------------------
  # Cloudfront Distributions
  # -----------------------------------

  HourofcodeDotComRedirectDistribution1:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: Redirects via CloudFront functions
        PriceClass: PriceClass_All
        Aliases: 
          - hourofcode.co
          - hourofcode.net
          - hourofcode.co.uk
          - hourofcode.org.uk
          - onehourofcode.com
          - onehourofcode.org
          - dayofcode.com
          - dayofcode.org
          - monthofcode.com
          - weekofcode.org
          - weekofcode.com
        Origins:
          # An origin is required, but will never receive traffic
          - Id: PrimaryOrigin
            DomainName: example.com
            CustomOriginConfig:
              OriginProtocolPolicy: match-viewer
        DefaultCacheBehavior:
          TargetOriginId: PrimaryOrigin
          CachePolicyId: !Ref RedirectCachePolicy
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !Ref RedirectCloudfrontFunctionHourofcodeCom
          ViewerProtocolPolicy: allow-all
          # Use shared Realtime Log config
          RealtimeLogConfigArn: !ImportValue AccessLogs-Config
        ViewerCertificate:
          AcmCertificateArn: !Ref HourofcodeDotComRedirectCertificate1
          SslSupportMethod: sni-only

  HourofcodeDotComRedirectCertificate1:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: hourofcode.co
      SubjectAlternativeNames:
        - hourofcode.net
        - hourofcode.co.uk
        - hourofcode.org.uk
        - onehourofcode.com
        - onehourofcode.org
        - dayofcode.com
        - dayofcode.org
        - monthofcode.com
        - weekofcode.org
        - weekofcode.com
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: hourofcode.co
          HostedZoneId: !Ref HourofcodeDotCoHostedZone
        - DomainName: hourofcode.net
          HostedZoneId: !Ref HourofcodeDotNetHostedZone
        - DomainName: hourofcode.co.uk
          HostedZoneId: !Ref HourofcodeDotCoDotUkHostedZone
        - DomainName: hourofcode.org.uk
          HostedZoneId: !Ref HourofcodeDotOrgDotUkHostedZone
        - DomainName: onehourofcode.com
          HostedZoneId: !Ref OnehourofcodeDotComHostedZone
        - DomainName: onehourofcode.org
          HostedZoneId: !Ref OnehourofcodeDotOrgHostedZone
        - DomainName: dayofcode.com
          HostedZoneId: !Ref DayofcodeDotComHostedZone
        - DomainName: dayofcode.org
          HostedZoneId: !Ref DayofcodeDotOrgHostedZone
        - DomainName: monthofcode.com
          HostedZoneId: !Ref MonthofcodeDotComHostedZone
        - DomainName: weekofcode.org
          HostedZoneId: !Ref WeekofcodeDotOrgHostedZone
        - DomainName: weekofcode.com
          HostedZoneId: !Ref WeekofcodeDotComHostedZone

  # -----------------------------------
  # Cloudfront Functions
  # -----------------------------------

  # Function redirect to code.org
  RedirectCloudfrontFunctionCodeOrg:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to code.org
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://code.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # Function redirect to csedweek.org
  RedirectCloudfrontFunctionCsedweekOrg:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to csedweek.org
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://csedweek.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # Function redirect to studio.code.org
  RedirectCloudfrontFunctionStudioCodeOrg:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to studio.code.org
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://studio.code.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # Function redirect to support.code.org
  RedirectCloudfrontFunctionSupportCodeOrg:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to support.code.org
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://support.code.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # Function redirect to uk.code.org
  RedirectCloudfrontFunctionUkCodeOrg:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to uk.code.org
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://uk.code.org';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # Function redirect to hourofcode.com
  RedirectCloudfrontFunctionHourofcodeCom:
    Type: AWS::CloudFront::Function
    Properties: 
      Name: !Sub "${AWS::StackName}-www-redirect"
      FunctionConfig: 
        Comment: Redirects to hourofcode.com
        Runtime: cloudfront-js-1.0
      AutoPublish: true
      FunctionCode: |
        function handler(event) {
          var newUrl = 'https://hourofcode.com';

          // Append path
          newUrl += event.request.uri;

          return {
            statusCode: 301,
            statusDescription: '301 Redirect to root domain',
            headers: {
              "location": { "value": newUrl }
            }
          };
        };

  # -----------------------------------
  # Common Resources
  # -----------------------------------

  # This cache policy is shared by all Cloudfront Distributions in this stack.
  RedirectCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: !Sub "${AWS::StackName}-redirect-policy"
        MinTTL: 3600
        MaxTTL: 31536000
        DefaultTTL: 86400
        ParametersInCacheKeyAndForwardedToOrigin:
          EnableAcceptEncodingGzip: false
          CookiesConfig: 
            CookieBehavior: none
          HeadersConfig: 
            HeaderBehavior: whitelist
            Headers:
              - Origin
          QueryStringsConfig: 
            QueryStringBehavior: all
