version: "3"
services:
  site:
    image: codedotorg/code-dot-org:ubuntu-20
    user: ${FIXUID:-1000}:${FIXGID:-1000}
    volumes:
      - ../:/home/circleci/code-dot-org:delegated
      - rbenv:/home/circleci/.rbenv
      - mysqldata:/var/lib/mysql
      - yarncache:/home/circleci/.cache
      - gcloud_config:/home/circleci/.config/gcloud
      - $HOME/.aws:/home/circleci/.aws
    environment:
      - AWS_PROFILE
    env_file:
      - env.list
    command: bash -c "bin/cron/create_rollup_tables"

volumes:
  mysqldata:
  rbenv:
  yarncache:
  gcloud_config:
