apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:   
  name: aws-google
  metadata:
    labels:
      app: dashboard
spec:
  resources:
    requests:
      storage: 5Mi  
  accessModes:
    - ReadWriteMany