name: Skaffold
on: [push]
jobs:
  build:
    name: Skaffold Build
    runs-on: ubuntu-22.04
    container:
      image: gcr.io/k8s-skaffold/skaffold:v2.6.3-lts
      # env:
      #   NODE_ENV: development
      # ports:
      #   - 80
      # volumes:
      #   - my_docker_volume:/volume_mount
      # options: --cpus 1
    env:
      SKAFFOLD_DEFAULT_REPO: docker.io/snickellcdo
    steps:
      - run: |
          echo hi
          echo "SKAFFOLD_DEFAULT_REPO=$SKAFFOLD_DEFAULT_REPO"
          echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ vars.K8S_DOCKEHUB_REPOSITORY }}
          username: ${{ vars.K8S_DOCKERHUB_USERNAME }}
          password: ${{ secrets.K8S_DOCKERHUB_TOKEN }}
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Skaffold Cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.skaffold/cache"
          key: skaffold-${{ hashFiles('**/cache') }}
          restore-keys: |
            skaffold-
      - run: |
          skaffold build \
            --push \
          && true



  quicktest:
    name: Quick Test
    runs-on: ubuntu-22.04
    # container: 
    #   image: alpine
    steps:
      - run: |
          env
          git clone https://github.com/code-dot-org/code-dot-org.git
  #         env
  #         echo hi
  #         echo "DIRECT K8S_DOCKERHUB_REPOSITORY=$K8S_DOCKERHUB_REPOSITORY"
  #         echo "K8S_DOCKEHUB_REPOSITORY=${{ vars.K8S_DOCKEHUB_REPOSITORY }}"
  #         echo "SKAFFOLD_DEFAULT_REPO=$SKAFFOLD_DEFAULT_REPO"
  #         echo "GITHUB_WORKFLOW=${GITHUB_WORKFLOW}"
  #       env:
  #         SKAFFOLD_DEFAULT_REPO: ${{ vars.K8S_DOCKEHUB_REPOSITORY }}
  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         registry: ${{ secrets.K8S_DOCKEHUB_REPOSITORY }}
  #         username: ${{ secrets.K8S_DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.K8S_DOCKERHUB_TOKEN }}
