name: Test Results Reporter
on:
  check_suite:
    types: [completed]
# on:
#   push:
#     branches:
#       - 'seth/github-action-*'
jobs:
  test-reporter:
    runs-on: ubuntu-latest
    steps:
      # Why does dorny/test-reporter want a git checkout??? heck knows
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Test Results
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://cdo-test-results-public/$GITHUB_SHA
          # source: s3://cdo-test-results-public/0fd1c41d87ee9662a0474a245324ee0f12be0574/
          destination: ./test-results
          aws_region: us-west-2
          flags: --recursive --no-sign-request

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Tests
          path: ./test-results/**/*.xml
          reporter: java-junit