name: Test Results Reporter
# on:
#   push:
#     branches:
#       - 'seth/github-action-*'

# Looks like deep in drone go land its generating a GH deployment status update message
#
# Drone source, see path schema: https://github.com/drone/go-scm/blob/f4a311024d4ece31370f2bd1bf90d0248852e57a/scm/driver/github/repo.go#L174
# 	path := fmt.Sprintf("repos/%s/deployments/%d/statuses", repo, input.Number)
#   this then gets posted
#
# GH API docs for creating a deployment status: https://docs.github.com/en/rest/deployments/statuses?apiVersion=2022-11-28#create-a-deployment-status--code-samples
# POST /repos/{owner}/{repo}/deployments/{deployment_id}/statuses
on:
  deployment_status:

jobs:
  test-reporter:
    if: |
      ( github.event.deployment_status.state == 'success' || github.event.deployment_status.state == 'failure' ) 
      && contains(github.refs, 'seth')
    runs-on: ubuntu-latest
    steps:
      # Why does dorny/test-reporter want a git checkout??? heck knows
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Test Results
        uses: keithweaver/aws-s3-github-action@v1.0.0
        with:
          command: cp
          source: s3://cdo-test-results-public/$GITHUB_SHA
          # source: s3://cdo-test-results-public/0fd1c41d87ee9662a0474a245324ee0f12be0574/
          destination: ./test-results
          aws_region: us-west-2
          flags: --recursive --no-sign-request

      - name: Generate Test Report
        uses: dorny/test-reporter@v1
        with:
          name: Tests
          path: ./test-results/**/*.xml
          reporter: java-junit
